### ISSUE TITLE
无法解密mgg格式

### ISSUE THREAD

**Issue by clan4456** [jixunmoe/qmc2#10]
QQ音乐版本：v18.51.0
Windows版本：Windows 11 Home 22000.856

mflac可正确解密，但mgg格式不能解密，见下图

![image](https://user-images.githubusercontent.com/48664247/185761335-870d0f78-01f4-4512-b54d-42458fcff35f.png)

**Comment by jixunmoe** [comment]
需要提供样本文件测试。或者文件的前后 1K 左右内容。可以直接作为附件上传到该 issue 内。

**Comment by jixunmoe** [comment]
> 谢霆锋 - 活着Viva.mflac 我使用 https://github.com/ZogeMung/DecrypeMusic 成功解密得到 flac 文件 使用 https://jixunmoe.github.io/qmc2 的话会给我一个 bin 文件，然后这个文件改成 flac 也不能播放呢。
> 
> [谢霆锋 - 活着Viva.zip](https://github.com/jixunmoe/qmc2/files/9604865/-.Viva.zip)

这是新版的加密，目前没有公开的算法能完美解密。你提到的项目就是 Unlock Music 旧版的预编译版，基于[已知明文攻击](https://zh.wikipedia.org/wiki/%E5%B7%B2%E7%9F%A5%E6%98%8E%E6%96%87%E6%94%BB%E5%87%BB)的方法来对数据进行一定的假设而解密。不能支持所有该类型加密的数据。

在文件的结尾你可以看到这一串字符：

![image](https://user-images.githubusercontent.com/5713045/191251807-f2f00a48-29ed-48c0-8fa8-9f9bd6f6ee74.png)

使用 Base64 解码选中区域后可以看到 `QQMusic EncV2` 字样。带有该字样的密钥衍生方法未知。

**Comment by jixunmoe** [comment]
已实现。

**Comment by Winwinnoa** [comment]
> 

请问这个能实现mflac转flac吗
