### ISSUE TITLE
mgg1 好像又失效了，貌似是更新了key

### ISSUE THREAD

**Issue by xin2233** [jixunmoe/qmc2#11]
![image](https://user-images.githubusercontent.com/49447535/194734717-52b63f21-6b4c-4508-9f6c-24650e6453a4.png)

如上图，在解密过程中提示： could not derive embedded ekey from file.

**Comment by xin2233** [comment]
好

**Comment by jixunmoe** [comment]
没有文件，无法进行验证。

**Comment by jixunmoe** [comment]
`STag` 是新的安卓版 - 里面没有密钥。请使用旧版本。

**Comment by zjns** [comment]
如有需要可以用我这个 [Xposed](https://github.com/zjns/QMHelper) 模块，直接调用APP方法批量解密。

**Comment by jixunmoe** [comment]
> 如有需要可以用我这个 [Xposed](https://github.com/zjns/QMHelper) 模块，直接调用APP方法批量解密。

已添加到百科：[同类项目](https://github.com/jixunmoe/qmc2/wiki/%E5%90%8C%E7%B1%BB%E9%A1%B9%E7%9B%AE#q-%E9%9F%B3%E5%8A%A9%E6%89%8B-%E5%AE%89%E5%8D%93-xposed-%E6%A8%A1%E5%9D%97)

**Comment by zjns** [comment]
> > 如有需要可以用我这个 [Xposed](https://github.com/zjns/QMHelper) 模块，直接调用APP方法批量解密。
> 
> 已添加到百科：[同类项目](https://github.com/jixunmoe/qmc2/wiki/%E5%90%8C%E7%B1%BB%E9%A1%B9%E7%9B%AE#q-%E9%9F%B3%E5%8A%A9%E6%89%8B-%E5%AE%89%E5%8D%93-xposed-%E6%A8%A1%E5%9D%97)

现在Xposed使用已经比较方便啦，不用root都行，可以用 [LSPatch](https://github.com/LSPosed/LSPatch) 把模块内置进宿主APP使用。

**Comment by xin2233** [comment]
感谢大家。
目前已通过下载旧版本解决此问题。

**Comment by jixunmoe** [comment]
> > > 如有需要可以用我这个 [Xposed](https://github.com/zjns/QMHelper) 模块，直接调用APP方法批量解密。
> > 
> > 
> > 已添加到百科：[同类项目](https://github.com/jixunmoe/qmc2/wiki/%E5%90%8C%E7%B1%BB%E9%A1%B9%E7%9B%AE#q-%E9%9F%B3%E5%8A%A9%E6%89%8B-%E5%AE%89%E5%8D%93-xposed-%E6%A8%A1%E5%9D%97)
> 
> 现在Xposed使用已经比较方便啦，不用root都行，可以用 [LSPatch](https://github.com/LSPosed/LSPatch) 把模块内置进宿主APP使用。

没看到百科之类的文档，没看代码的情况下不是很清楚怎么实现的。

如果是注入代码到 apk 后重打包，那必然会改变应用签名，那之后就是签名检测方面的对抗了。

不过确实能让 xposed 模块变得更方便，会将这部分信息加入百科。
