### ISSUE TITLE
转换后的音乐文件没有封面

### ISSUE THREAD

**Issue by tachikomachann** [jixunmoe/qmc2#13]
我试了从mflac转换到flac，用mp3tag查看后发现没有专辑封面图片。

**Comment by tachikomachann** [comment]
导入自带的emby server后封面又是正常的，可能是我哪里搞错了。closed

**Comment by jixunmoe** [comment]
软件只负责解码文件，不对元信息进行修正、补充。因为这需要识别文件信息并与腾讯服务器进行通讯。
导入到第三方软件后显示正常可能因为你配置了自动刮削，然后通过现有的元信息或声纹匹配自动补充了缺少的元信息。

**Comment by Winwinnoa** [comment]
可以分享下解码文件吗

**Comment by jixunmoe** [comment]
@Winwinnoa  有问题请开新的 issue 询问
