### ISSUE TITLE
Decrypt incorrectly while success is still true

### ISSUE THREAD

**Issue by xhacker-zzz** [jixunmoe/qmc2#14]
![屏幕截图 2022-11-06 162053](https://user-images.githubusercontent.com/63585800/200161266-74d9e808-cd43-41e0-8b0e-d92d65cd59ab.jpg)
![屏幕截图 2022-11-06 162449](https://user-images.githubusercontent.com/63585800/200161269-0c104f5b-0997-45cb-9359-80e39e4b94ba.jpg)

**Comment by xhacker-zzz** [comment]
Using v3.mflac as a sample in the Telegram group.

**Comment by jixunmoe** [comment]
之后的版本会在 tea 解密后进行错误检查，若是解密失败则退出。
