### ISSUE TITLE
关于支持格式问题

### ISSUE THREAD

**Issue by Not-a-good-username** [jixunmoe/qmc2#4]
您好，刚刚测试了一下，您的工具其实也是支持Qtag结尾的mflac0的，解码后可以成功生成可播放的flac编码文件，希望您能够进行补充，谢谢。（这个应该不难吧？）

**Comment by Not-a-good-username** [comment]
应该markdown里头提醒一下大家就行？

**Comment by jixunmoe** [comment]
好 会加上
