### ISSUE TITLE
Can not decode the new version of mflac format...

### ISSUE THREAD

**Issue by RoyHANABI** [jixunmoe/qmc2#6]
Maybe the codec has been rebuilt...please check.

**Comment by jixunmoe** [comment]
Help needed to reverse VMProtect protected binaries.

**Comment by zeroclear** [comment]
https://github.com/zeroclear/unlock-mflac-20220931

**Comment by jixunmoe** [comment]
> https://github.com/zeroclear/unlock-mflac-20220931

感谢，开始研究

**Comment by jixunmoe** [comment]
已经实现，感谢 @zeroclear 逆向的过程。
