### ISSUE TITLE
ERROR: could not derive embedded ekey from file

### ISSUE THREAD

**Issue by zollty** [jixunmoe/qmc2#7]
D:\__SYNC1>QMC2-decoder.x86_64.exe "D:\__SYNC\dd.mflac0" "aa.flac"
QMC2 decoder (cli) v0.0.6 by Jixun

ERROR: could not derive embedded ekey from file.
       unknown magic: 67615453-18000000

mflac0 is not supported？

**Comment by jixunmoe** [comment]
Please upload the original file for analyse and provide the client version/platform where the file was downloaded.

Do note that mflac file downloaded from latest Windows client is not supported, see #6.

---

请上传原始文件供分析，并提供下载该文件所使用的客户端版本、平台。

请注意目前最新版 Windows 客户端下载的加密文件暂不支持，参见 #6。

**Comment by jixunmoe** [comment]
得到平台/版本信息后，会更新兼容说明。

[支持的客户端](https://github.com/jixunmoe/qmc2/wiki/%E6%94%AF%E6%8C%81%E7%9A%84%E5%AE%A2%E6%88%B7%E7%AB%AF)

**Comment by jixunmoe** [comment]
根据错误提示（`67615453` = `STag`）得知该文件来自安卓最新版本的加密。

该项目不支持该类型文件，因为没有内置解密 key。详细分析可参见 https://github.com/unlock-music/unlock-music/discussions/278
